name=input("Enter the name")
print(name)
l=len(name)
print("lenght of string ",name," is",l)
b=name.lower()
print(name," in lower case is ",b)
c=name.swapcase()
print(name," after swapping case's is ",c)
d=max(name)
print("max of given string",name," is ",d)
e=min(name)
print("min of given string",name," is ",e)
f=name.lstrip("A")
print(f)